apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: bluegreens.mattermost.com
spec:
  group: mattermost.com
  names:
    kind: BlueGreen
    listKind: BlueGreenList
    plural: bluegreens
    singular: bluegreen
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            ingressAnnotations:
              additionalProperties:
                type: string
              type: object
            ingressName:
              description: IngressName defines the name to be used when creating the
                ingress rules
              type: string
            serviceAnnotations:
              additionalProperties:
                type: string
              type: object
            useServiceLoadBalancer:
              type: boolean
          required:
          - ingressName
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
